// Regenerates the text snapshot the "Ask about my work" assistant answers from.
// Run: bun scripts/build-portfolio-context.ts
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const tmp = "/tmp/portfolio-context";
mkdirSync(tmp, { recursive: true });
for (const f of ["projects", "projectsStructured"]) {
  const src = readFileSync(`src/data/${f}.ts`, "utf8")
    .replace(/^import (type )?\{[^}]*\} from .*$/gm, "")
    .replace(/^import ([A-Za-z0-9_]+) from .*$/gm, 'const $1: any = { url: "" };');
  writeFileSync(`${tmp}/${f}.ts`, src);
}
const { projectsData } = await import(`${tmp}/projects.ts`);
const { structuredProjects } = await import(`${tmp}/projectsStructured.ts`);

const MEDIA = /image|src|gallery|poster|video|thumb|logo|icon|media|cover|url/i;
const strip = (o: unknown): unknown =>
  Array.isArray(o)
    ? o.map(strip)
    : o && typeof o === "object"
      ? Object.fromEntries(Object.entries(o).filter(([k]) => !MEDIA.test(k)).map(([k, v]) => [k, strip(v)]))
      : o;

const json = JSON.stringify({ projects: strip(projectsData), caseStudies: strip(structuredProjects) });
writeFileSync(
  "supabase/functions/ask-portfolio/portfolio-context.ts",
  `// Auto-generated by scripts/build-portfolio-context.ts. Do not edit by hand.\nexport const PORTFOLIO_CONTEXT = ${JSON.stringify(json)};\n`,
);
console.log("portfolio context bytes:", json.length);
